apiVersion: v1
kind: Service
metadata:
  name: sygnal
  namespace: matrix
  labels:
    app: sygnal
spec:
  type: ClusterIP
  selector:
    app: sygnal
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
